#!/bin/bash
# A script to backup / restore arbitrary system files from multiple hosts to a 
# shared, versioned location, while caring for file permissions (mod, uid,gui).
# The script is based on aboslut pathes, to support system files.
# Versioning is done in git, while each hosts has it's own branch.
#
# Depends: git, getfacl setfacl
#
# TODO: 
#   - merge from other host
#   - restore "all"
#   - show diff
#   - run as user. Request root if necessary.
#   - create arch configuration packages?
#   - support recursive directories

REPO="/mnt/extHDD/backup/cfgbak.git"
_cmd=$1
SRC=$2
# get command line arguments and set cfg_ variables
unset OPTIND
unset OPTARG
while getopts hvd _opts
do
    case ${_opts} in
        d)
            echo "Dry-run. No file modificaions !!"
            DRYRUN=true
            ;;
        v)
            VERBOSE=true
            ;;
        # c)
            # CMD=${OPTARG}
            # ;;
        h)
            echo "Usage: cfgbak [OPTION] [store, restore] FILE"
            echo "  -d      Dry run."
            echo "  -v      verbose"
            exit 2
            ;;
        *)
            echo "Error, unknown parameter"
            exit 2
            ;;
    esac
done
CMD=${@:$OPTIND:1}
SRC=${@:$OPTIND+1:1}

# function to execute cmd's, or just print them for dry run
function EXEC {
    if [ ${DRYRUN} ]; then
        echo "# ${1}"
    else
        ${1}
    fi
}

if [ ${VERBOSE} ]; then
    echo "CMD       : ${CMD}"
    echo "SRC       : ${SRC}"
    [ ${DRYRUN} ] && echo "Dry-run   : true"
    echo "Repo      : ${REPO}"
fi

# create a new repo, if it does not exists
if [ ! -d ${REPO} ]; then
    echo "Error, no repo at ${REPO}"
    EXEC "git init ${REPO}"
fi
[ ! -f ${SRC} ] && echo "Error, src not found" && exit
[ ! ${SRC:0:1} == "/" ] && echo "Error, src not absolut" && exit
# if [ ${SRC:0:1} == "/" ]; then
    # DST=${SRC:1}
# else
    DST=${REPO}${SRC}
# fi

case ${CMD} in
    store)
        echo "-> store ${SRC} to ${DST}"
        # if dst path not exists, create
        _base=$(dirname ${DST})
        [ ! -d ${_base} ] && EXEC "mkdir -p ${_base}"
        #TODO: store permissions of path
        EXEC "cp -rf ${SRC} ${DST}"
        # store file permissions
        EXEC "getfacl ${SRC} > ${DST}.facl"
        ;;
    restore)
        echo "restore ${DST} to ${SRC}"
        # check if exist
        # copy
        # if fail, maybe we miss permission -> sudo
        # set permissions
        ;;
    *)
        echo "Error, unknown command!"
        exit
        ;;
esac
